@startuml
'https://plantuml.com/component-diagram


package "UI" {
  [ShortenerService]
}

package "Web Api" {
  HTTP - [ShortLinkController]
  [ShortLinkController] --> [ILinkConverterCommand]
}

package "Infrastructure" {
   [ShortenerService.Infra] --> [UserService]
   [ShortenerService.Infra] --> [Uow]
   [UserService] --> [Uow]
   frame DataAccess {
    [Uow] -->  [Repositories]
    [Uow] --> [ApplicationDbContext]
   }
}

package "Application logic" {
    frame Services {
        [ILink] <.. [Link]
        [Link] <|- [ConverterService]
        [ConverterService] --> [ILink]
        [ILink] <-- [QrLink]
        [ILink] <-- [TextLink]
    }
    frame Entities {
      [Url]
      [User]
    }
    frame Dto {
      [LinkDto]
    }
}


database "SqlServer" {
  frame "LinkShortenerDb" {
    [Url]
    [User]
  }
}


[ShortenerService] --> [ShortLinkController]
[DataAccess] --> [LinkShortenerDb]
[ILinkConverterCommand] --> [ConverterService]
[ShortLinkController] --> [ShortenerService.Infra]
@enduml